// <auto-generated />
using System;
using IssueBridge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueBridge.Api.Migrations
{
    [DbContext(typeof(IssueBridgeDbContext))]
    partial class IssueBridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("IssueBridge.Api.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GitHubCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("GitHubUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubIssueId")
                        .IsUnique();

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("IssueBridge.Api.Models.LocalTaskInfo", b =>
                {
                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("IssueId");

                    b.ToTable("LocalTaskInfos");
                });

            modelBuilder.Entity("IssueBridge.Api.Models.LocalTaskInfo", b =>
                {
                    b.HasOne("IssueBridge.Api.Models.Issue", "Issue")
                        .WithOne("LocalTaskInfo")
                        .HasForeignKey("IssueBridge.Api.Models.LocalTaskInfo", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("IssueBridge.Api.Models.Issue", b =>
                {
                    b.Navigation("LocalTaskInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
